#!/bin/sh
# thin-edge.io log plugin: retrieve logs of managed containers from Cumulocity
# (Device Management > Logs). Delegates to the tedge-container multi-call binary.
exec /opt/tedge/bin/tedge-container log-plugins container "$@"
